version: "3"

services:
  speedtest:
    build:
      context: .
      args:
        TARGETPLATFORM: linux/amd64
    environment:
      - INTERVAL=60
      - HOST=myhost
      - INFLUXDB_URL=http://myinfluxdb.local
      - INFLUXDB_NAME=db
