version: "3"

services:
  speedtest:
    build:
      context: .
      args:
        TARGETPLATFORM: linux/amd64
    environment:
      - INTERVAL=60
      - SPEEDTEST_SERVER_ID=30907
      - HOST=myhost
      - INFLUXDB_URL=http://myinfluxdb.local
      - INFLUXDB_ORG=myorg
      - INFLUXDB_BUCKET=mybucket
      - INFLUXDB_TOKEN=mytoken
